from util import query
from pprint import pprint

print("Q1. Find investors who are making on average a loss across all their portfolios in 2024.")
res = query("queries/q1.sql")
pprint(res)
print("\n")
print("Q2. Find investors who are seeing an annualized return of more than 10% from their portfolios in 2024.")
res = query("queries/q2.sql")
pprint(res)
print("\n")
print("Q3. Find the monthly average unrealized gain/loss of portfolios for each month in 2024.")
res = query("queries/q3.sql")
pprint(res)
print("\n")
print("Q4. What is the top three most popular first financial goals for investors in 2024?")
res = query("queries/q4.sql")
pprint(res)
print("\n")
print("Q5. Find investors who consistently top up their investment at the beginning of every month (dollar-cost averaging) in 2024 for at least one of their portfolios.")
res = query("queries/q5.sql")
pprint(res)
print("\n")
print("Q6. Find the most popular financial goals for investors working in the same company and whose age is between 30 to 40 years old.")
res = query("queries/q6.sql")
pprint(res)
print("\n")
print("Q7. Are male investors in their 20s making more money from their investments than their female counterparts in 2024?")
print("a: per PERSON basis")
res = query("queries/q7a.sql")
pprint(res)
print("\n")
print("a: per PORTFOLIO basis")
res = query("queries/q7b.sql")
pprint(res)
print("\n")